/*
 * generated by Xtext 2.9.0
 */
package de.bosch.ebike.datamodel.idea.completion

import de.bosch.ebike.datamodel.idea.lang.RootModelLanguage
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage

class RootModelCompletionContributor extends AbstractRootModelCompletionContributor {
	new() {
		this(RootModelLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
