/*
 * generated by Xtext 2.9.0
 */
package de.bosch.ebike.datamodel.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class RootModelIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new RootModelStandaloneSetupIdea().createInjector
	}

}
