/*
 * generated by Xtext 2.9.0
 */
package de.bosch.ebike.datamodel.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class RootModelIdeaModule extends AbstractRootModelIdeaModule {
}
