/*
 * generated by Xtext 2.9.0
 */
package de.bosch.ebike.datamodel.idea.lang


class RootModelFileType extends AbstractRootModelFileType {
	public static final RootModelFileType INSTANCE = new RootModelFileType()
	
	new() {
		super(RootModelLanguage.INSTANCE)
	}
}
