/*
 * generated by Xtext 2.9.0
 */
package de.bosch.ebike.datamodel.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class RootModelProposalProvider extends AbstractRootModelProposalProvider {
}
